name: C++ CI Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build-windows:
    # Uses GitHub-hosted Windows runner with Makefile
    if: ${{ true }}
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Make
        run: choco install make

      - name: Build and Test on Windows
        run: |
          make
          ./test_sum.exe

  build-linux:
    # Linux build using Makefile
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test on Linux
        run: |
          make
          ./test_sum

  build-custom:
    # Custom environment build using Makefile
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Custom Environment Build and Test
        run: |
          make
          ./test_sum

  conan-publish:
    # Only runs on master branch
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conan
        run: pip install conan

      - name: Export and Upload Conan Package
        run: |
          conan export . sum_project/1.0@
